### ISSUE TITLE
It seems that the query has not been effective

### ISSUE THREAD

**Issue by zxyAcmen** [travisbrown/memory.lol#33]
![image](https://github.com/user-attachments/assets/6edee519-875a-4421-ba32-52d42894d177)
The picture shows me manually changing the name of my Twitter account just now, but when I tried to check, no account record information was returned

**Comment by travisbrown** [comment]
The service does not access any X API and is not real-time. Changes are reflected only when the database is updated from web archives (the Wayback Machine, etc.).

**Comment by zxyAcmen** [comment]
> The service does not access any X API and is not real-time. Changes are reflected only when the database is updated from web archives (the Wayback Machine, etc.).

Thank you, I understand. I would like to query some previous name change records through your API. What should I do to be allowed.

**Comment by zxyAcmen** [comment]
Yes, I have looked at your memory.lol project and I think it can be very helpful to many people. I am eager to obtain API call permissions. I sent you an email, but did not receive a reply. I hope to receive your help. Thank you!
