### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by DonkeyXBT** [travisbrown/memory.lol#34]
The website does not give any response, but only the ones that are in readme file work with this

**Comment by travisbrown** [comment]
Yes, it still works, but full history search is limited to a small set of approved authenticated users.

**Comment by DonkeyXBT** [comment]
> Yes, it still works, but full history search is limited to a small set of approved authenticated users.

Is it possible for me to get access to the full history search? I cannot find you on twitter to dm you.

**Comment by travisbrown** [comment]
My Twitter account was suspended (there's an article about the suspension [here](https://www.wired.com/story/x-twitter-ban-critics/)). You can email me with details, but to be honest I haven't approved many requests recently and can't guarantee that I'll respond (this isn't related to my day job and I don't have a lot of time at the moment).

**Comment by Tgaines412** [comment]
@travisbrown ill pay you for full access @gener412 on discord i got good money for u need it for my project
