### ISSUE TITLE
Service returns 403 error

### ISSUE THREAD

**Issue by domingroso** [travisbrown/memory.lol#8]
Hi, worked fine last night. But today all requests return a 403 error from Nginx. Is everything ok over there?
![403 memory lol](https://user-images.githubusercontent.com/26884721/179069050-f94ff0c3-b2c7-40a2-8a19-5d1d7e5ab575.png)

**Comment by naresh97** [comment]
see:
https://github.com/travisbrown/memory.lol/issues/3#issuecomment-1184302473

**Comment by domingroso** [comment]
Got it, thank you.
