### ISSUE TITLE
403 on demo link in read-me

### ISSUE THREAD

**Issue by raed667** [travisbrown/memory.lol#9]
The first demo link provided in the readme returns an NGINX 403

https://memory.lol/tw/libsoftiktok

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1442690/179190904-45a9676e-463f-4621-bbb5-931a4823dd14.png">

**Comment by travisbrown** [comment]
This is being tracked in #3. It's likely that a limited public version will be rolled out this weekend, with the complete index being available to trusted users.
